// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.andrewswan.gamenight.domain.club;

import com.andrewswan.gamenight.domain.club.Club;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Club_Roo_Configurable {
    
    declare @type: Club: @Configurable;
    
}
